### ISSUE TITLE
New-MessageReceiver: Cleanup required

### ISSUE THREAD

**Issue by dfch** [dfensgmbh/biz.dfch.PS.Azure.ServiceBus.Client#10]
The code in `New-MessageReceiver.ps1` contains a `Credential` input parameter that is not really used.  This must be fixed.

In addition, there are code parts which are not maintainable (3line if statements) - fix as well.

Why is `PeekLock` the default behaviour? I think we agreed on `ReceiveAndDelete` as the default.

In general I would recommend to rename the Cmdlet from `New-MessageReceiver` to `Get-MessageReceiver` or something with `Factory` is this is actually more hinting at its use.

Inline help not consistent or giving meaningful information.

Why is this Cmdlet exported? does anyone external call this? or is it more like an internal Cmdlet?

**Comment by schefDev** [comment]
Resolved with 
https://github.com/dfensgmbh/biz.dfch.PS.Azure.ServiceBus.Client/commit/e5419074a8bec22bea4de60dfed04a76b3a0ce4b
