### ISSUE TITLE
Problem when sending or receiving messages

### ISSUE THREAD

**Issue by gaestu** [dfensgmbh/biz.dfch.PS.Azure.ServiceBus.Client#12]
During long run tests with it appear few failer with receiving messages (3 failures in ~700 tests). 

The tests do not interrupt or get an error, but the assertion after the test is not right. The receiver gets to less messages.

**Comment by dfch** [comment]
@gaestu I suggest to run this for a 24h period (or during two consecutive nights) on LAB3 or INT11 and save the Pester results to a file (e.g. `-OutputXml`).
We will then have a look at it and determine the next steps.

A general note: when you have testing errors please always attach the error from the test run, so we can see which tests actually failed. This will also help us later to re-run a test after we have fixed something.

**Comment by dfch** [comment]
@gaestu pls attach the test reports to this issue

**Comment by gaestu** [comment]
Here you finde the Testresults [TestResults.zip.txt](https://github.com/dfensgmbh/biz.dfch.PS.Azure.ServiceBus.Client/files/43548/TestResults.zip.txt)

**Comment by rufer7** [comment]
@dfch do you know what's the status here?

**Comment by dfch** [comment]
@rufer7 no idea - we should ask @gaestu as soon as he is back , so that he can have a look at the reports and check if this is still an issue.

**Comment by rufer7** [comment]
@gaestu do we know anything more here?

**Comment by rufer7** [comment]
As @gaestu told me, this problem does not occur anymore and is not reproducable anymore. I would close the issue and we can reopen if the problem occurs again.

@gaestu please attach xml reports
