### ISSUE TITLE
Release required

### ISSUE THREAD

**Issue by dfch** [dfensgmbh/biz.dfch.PS.Azure.ServiceBus.Client#13]
* consider to release `1.0.0`

@rufer7 what do you think?

**Comment by rufer7** [comment]
If it's stable `1.0.0` is a good starting point

**Comment by dfch** [comment]
@schefDev are there any pending updates on this repo? or can we make a stable release?

**Comment by schefDev** [comment]
@dfch no pending updates exist on this repo (stable release).
