### ISSUE TITLE
DLLs inside src folder

### ISSUE THREAD

**Issue by dfch** [dfensgmbh/biz.dfch.PS.Azure.ServiceBus.Client#7]
There are several DLLs inside the `src` folder of this repository. Some of them are third party libraries that do not fall under the Apache 2.0 license. These files must not be part of this repository, but might be only included in the NuGet package.

Please remove all unnecessary files.

**Comment by schefDev** [comment]
Resolved with
https://github.com/dfensgmbh/biz.dfch.PS.Azure.ServiceBus.Client/commit/79565d8b764c1bc898f578d460c99f0f1523b1d6
